name: Setup Environment
description: Install Node.js and repository setup

inputs:
  node-version-file:
    description: Node.js version file path
    required: false
    default: .nvmrc
  args:
    description: Arguments passed to `pnpm run setup`
    required: false
    default: '--frozen-lockfile'
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v6  
      with:  
        cache: true

    - name: Setup Node.js  
      uses: actions/setup-node@v5  
      with:  
        node-version-file: ${{ inputs.node-version-file }}

    - name: Install dependencies
      run: pnpm run setup ${{ inputs.args }}
      shell: bash
