name: Cleanup Deleted Users

on:
  schedule:
    - cron: '0 19 * * *' 
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and Pnpm
        uses: ./.github/actions/setup

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: Run Cleanup Script
        run: pnpm run db:cleanup-users
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}