# Test Workflow
#
# Runs Vitest tests in parallel.

name: Run Tests

on:
  workflow_call:

jobs:
  run-tests:
    name: Run ${{ matrix.test-type }} Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-type: [unit, integration]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Development Environment
        uses: ./.github/actions/setup