# System Test Workflow
#
# Runs Playwright system tests.

name: Run System Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run-system-tests:
    name: Run System Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Setup Development Environment
        uses: ./.github/actions/setup

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Seed Development Database For System Tests
        run: pnpm exec tsx scripts/db.ts seed

      - name: Run System Tests
        run: pnpm run test:system
