name: Verify Docs Build

on:
  pull_request:
    branches: ["main"]
    paths:
      - 'docs/**'
      - '.github/workflows/verify-docs-build.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Development Environment
        uses: ./.github/actions/setup
        with:
          args: '--frozen-lockfile --filter docs --ignore-scripts'

      - name: Build with VitePress
        working-directory: docs
        run: pnpm build
